### ISSUE TITLE
AttributeError: 'PregTool' object has no attribute 'GetRegistryHelpers'

### ISSUE THREAD

**Issue by majordjuj** [log2timeline/l2tpreg#25]
Hello,

I'm facing an issue with preg.py, I'm unable to use the console session mode with preg.py : 

```
user@workstation -> ~/D/S 
$ preg.py -i image.img -c SYSTEM
Traceback (most recent call last):
  File "/usr/local/bin/preg.py", line 4, in <module>
    __import__('pkg_resources').run_script('l2tpreg==20180329', 'preg.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/l2tpreg-20180329-py2.7.egg/EGG-INFO/scripts/preg.py", line 838, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/l2tpreg-20180329-py2.7.egg/EGG-INFO/scripts/preg.py", line 832, in Main
    
  File "/usr/local/lib/python2.7/dist-packages/l2tpreg-20180329-py2.7.egg/EGG-INFO/scripts/preg.py", line 670, in Run
    
AttributeError: 'PregTool' object has no attribute 'GetRegistryHelpers'
```

Even if I try to open the console session directly from a mounted image and on one and only one hive : 

```
$ preg.py -c NTUSER.DAT
Traceback (most recent call last):
  File "/usr/local/bin/preg.py", line 4, in <module>
    __import__('pkg_resources').run_script('l2tpreg==20180329', 'preg.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/l2tpreg-20180329-py2.7.egg/EGG-INFO/scripts/preg.py", line 838, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/l2tpreg-20180329-py2.7.egg/EGG-INFO/scripts/preg.py", line 832, in Main
    
  File "/usr/local/lib/python2.7/dist-packages/l2tpreg-20180329-py2.7.egg/EGG-INFO/scripts/preg.py", line 670, in Run
    
AttributeError: 'PregTool' object has no attribute 'GetRegistryHelpers'
```
After that I tried to update the repo and reinstalled the dependencies with the requirement.txt file but still the same issue.
I don't know if something is wrong with l2tpreg==20180329, I can not find any previous version to try mitigate the issue.

Do you have any idea what is wrong ?

Thanks.

**Comment by joachimmetz** [comment]
I'll have a look to update l2preg once we've updated plaso

**Comment by joachimmetz** [comment]
Case: method was made protected (`leading underscore`) but still used by the tool.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/339680043/

**Comment by majordjuj** [comment]
Hello !

Many thanks, it solved my problem. I've updated my local repo and reinstall preg, and launched the preg.py -c NTUSER.DAT 

Works like a charm. :)

**Comment by joachimmetz** [comment]
@majordjuj thanks for confirming the changes fixed the issue for you.
